### 2.1数据操作

#### 读取写入数据

In [10]:
import torch

x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([16])

In [5]:
x.numel()

16

In [11]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
x = x.reshape(6,-1)
x

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [16]:
torch.zeros((2, 3,4))  # 全0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
print(torch.ones((3,4,5)))  # 传入一个元组
print(torch.ones(3,4,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [18]:
torch.randn(3,4)

tensor([[ 0.3439, -0.1357,  0.8815,  0.9000],
        [ 0.9647,  0.3105, -0.6356, -0.2871],
        [-0.8133, -1.2003, -0.0548, -0.1750]])

In [22]:
torch.tensor([[2,1,3,4],[6,6,6,6],[7,8,9,1]])

tensor([[2, 1, 3, 4],
        [6, 6, 6, 6],
        [7, 8, 9, 1]])

#### 数据运算

In [25]:
x = torch.tensor([1, 3 , 5, 7])
y = torch.tensor([2,4,6,8])
x, y, x+y, x-y, x*y, x/y, x**y

(tensor([1, 3, 5, 7]),
 tensor([2, 4, 6, 8]),
 tensor([ 3,  7, 11, 15]),
 tensor([-1, -1, -1, -1]),
 tensor([ 2, 12, 30, 56]),
 tensor([0.5000, 0.7500, 0.8333, 0.8750]),
 tensor([      1,      81,   15625, 5764801]))

In [26]:
torch.exp(x)

tensor([   2.7183,   20.0855,  148.4132, 1096.6332])

In [28]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2,1,3,4],[4,2,3,6],[9,6,3,1]])
x, y, torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)   # dim=0沿行连接， dim1 沿列链接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2, 1, 3, 4],
         [4, 2, 3, 6],
         [9, 6, 3, 1]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  4.],
         [ 4.,  2.,  3.,  6.],
         [ 9.,  6.,  3.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  4.,  2.,  3.,  6.],
         [ 8.,  9., 10., 11.,  9.,  6.,  3.,  1.]]))

In [29]:
x == y

tensor([[False,  True, False, False],
        [ True, False, False, False],
        [False, False, False, False]])

In [53]:
x > y, x<y

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [31]:
x.sum(), y.sum()  # 逐元素求和

(tensor(66.), tensor(44))

#### 广播机制

In [32]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a, b 

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [37]:
# a复制列， b复制行 广播成相同形状
a+b, a+b-b,a+b-a

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 0],
         [1, 1],
         [2, 2]]),
 tensor([[0, 1],
         [0, 1],
         [0, 1]]))

In [65]:
c = torch.arange(24).reshape(2,3,4)
d = torch.arange(12).reshape(2,3,2)
# c, d, c+d, c+d-d, c+d-c
c, d

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 5,  6,  7,  8],
          [10, 11, 12, 13]],
 
         [[15, 16, 17, 18],
          [20, 21, 22, 23],
          [25, 26, 27, 28]]]))

In [67]:
c = torch.arange(24).reshape(2,3,4)
d = torch.arange(6).reshape(2,3,1)
# c, d, c+d, c+d-d, c+d-c
c, d, c+d, c+d-d, c+d-c

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 5,  6,  7,  8],
          [10, 11, 12, 13]],
 
         [[15, 16, 17, 18],
          [20, 21, 22, 23],
          [25, 26, 27, 28]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[0, 0, 0, 0],
          [1, 1, 1, 1],
          [2, 2, 2, 2]],
 
         [[3, 3, 3, 3],
          [4, 4, 4, 4],
          [5, 5, 5, 5]]]))

#### 索引和切片

In [38]:
x, x[-1], x[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [39]:
x[1,2]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
x[0:2, :] = 12  # 沿着0,1行赋值
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

#### 节省内存

In [46]:
before = id(y)  # id返回内存地址
y = y + x

before, id(y), id(y) == before

(2911591593840, 2911591636480, False)

In [47]:
before = id(y)  # id返回内存地址
y[:] = y + x

before, id(y), id(y) == before

(2911591636480, 2911591636480, True)

In [48]:
before = id(y)  # id返回内存地址
y += x

before, id(y), id(y) == before

(2911591636480, 2911591636480, True)

#### 转换成其他python对象

In [50]:
a = x.numpy()
b = torch.tensor(a)
x, a, b, type(a), type(b)

(tensor([[11., 11., 12., 12.],
         [11., 11., 12., 12.],
         [11., 11., 10., 11.]]),
 array([[11., 11., 12., 12.],
        [11., 11., 12., 12.],
        [11., 11., 10., 11.]], dtype=float32),
 tensor([[11., 11., 12., 12.],
         [11., 11., 12., 12.],
         [11., 11., 10., 11.]]),
 numpy.ndarray,
 torch.Tensor)

In [51]:
A = torch.tensor([3.5])
A, A.item(), float(A), int(A)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.2数据预处理

#### 2.2.1读取数据集

In [70]:
import os

os.makedirs(os.path.join('..','data'), exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')

with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n')
    f.write('2,NA,56400\n')
    f.write('4,NA,88400\n')
    f.write('NA,NA,86400\n')

import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN   56400
2       4.0   NaN   88400
3       NaN   NaN   86400


#### 2.2.2处理缺失值

In [73]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] # 前者为data前两列，后者为最后一列
means = inputs.mean(numeric_only=True)
inputs = inputs.fillna(means)
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [74]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


#### 2.2.3转换成张量形式

In [80]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
Y = torch.tensor(outputs.to_numpy(dtype=float))
inputs,outputs, X, Y

(   NumRooms  Alley_Pave  Alley_nan
 0       3.0        True      False
 1       2.0       False       True
 2       4.0       False       True
 3       3.0       False       True,
 0    127500
 1     56400
 2     88400
 3     86400
 Name: Price, dtype: int64,
 tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500.,  56400.,  88400.,  86400.], dtype=torch.float64))

#### 2.2.4删除缺失值最多的列

In [81]:
data_copy = data.copy()
data_copy

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN   56400
2       4.0   NaN   88400
3       NaN   NaN   86400

In [82]:
# data.isnuLl（）会把所有 NaN 值标记为 True（计为1)，非 NaN 标记为False（计为θ)
#。sum（）会对每一列进行求和，从而得到每列NaN 的总数
missing_counts = data_copy.isnull().sum() 
missing_counts

NumRooms    2
Alley       3
Price       0
dtype: int64

In [83]:
#。idxmax（）会返回Series中最大值的索引（在这里，索引就是列名）
col_to_drop = missing_counts.idxmax()
col_to_drop

'Alley'

In [84]:
#使用.drop(）方法，指定列名和axis=1（表示操作对象是列)
data_copy = data_copy.drop(col_to_drop, axis=1)
data_copy

NumRooms   Price
0       NaN  127500
1       2.0   56400
2       4.0   88400
3       NaN   86400